apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-api
  description: Demo API
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: demo
  config:
    data:
      - file: entities.yaml
        path: ./entities.yaml
